Update the EBL directory
gammapy/gammapy-data pull request #50
Opened 2024-04-10 17:01 UTC by bkhelifi

This PR updates the references to the models, as well as the figure

2024-04-11 08:03 UTC, maxnoe requested changes
There is a typo in the legend for Francesch__i__ni 2017

2024-04-11 08:26 UTC, maxnoe approved these changes

2024-04-11 08:30 UTC, bkhelifi commented
Thanks @maxnoe. I am still waiting for the feedback from Finke, Dominguez ans Saldana-Lopez about the licence question.
I propose that we merge this PR once we have all the authors' information.

2024-04-15 16:58 UTC, bkhelifi commented
Add the licences are added. This PR is ready to be reviewed... @registerrier

2024-04-16 15:19 UTC, registerrier approved these changes
Thanks @bkhelifi . Looks good to me.

2024-04-16 15:21 UTC, registerrier commented on ebl/README.md
> +   evolution and the cosmic photon-photon opacity © 2008 by Alberto Franceschini -
A question. Is it just the first author here?

2024-04-16 15:21 UTC, registerrier commented on ebl/README.md
> +   evolution and the cosmic photon-photon opacity © 2017 by Alberto Franceschini -
Same.

2024-04-17 14:16 UTC, registerrier approved these changes
Thanks @bkhelifi !

2024-04-17 14:17 UTC, merged